### ISSUE TITLE
Prop for a separator?

### ISSUE THREAD

**Issue by niikkiin** [40818419/react-code-input#128]
Hi, Is there any way to add a separator for each input or after a certain input?
For example:
![image](https://user-images.githubusercontent.com/26428605/114455601-86349400-9c0e-11eb-8fee-7f4c9cea9d61.png)

**Comment by acusti** [comment]
i accomplished this via CSS (which felt appropriate, because it’s a matter of presentation). it’s a little trickier than it should be, because `input` elements don’t support `::before` / `::after` pseudo elements, but i used flex-box plus `order` with pseudo elements on the `.react-code-input` wrapper:
```css
.react-code-input {
    position: relative;
    display: flex;
    align-items: center;
    justify-content: center;
}

.react-code-input::before,
.react-code-input::after {
    content: "";
    margin: 0px 16px;
    width: 20x;
    height: 3px;
    background-color: #999;
}

.react-code-input input:nth-child(1) {
    order: 1;
}
.react-code-input input:nth-child(2) {
    order: 2;
}
.react-code-input input:nth-child(3) {
    order: 3;
}
.react-code-input::before {
    order: 4;
}
.react-code-input input:nth-child(4) {
    order: 5;
}
.react-code-input input:nth-child(5) {
    order: 6;
}
.react-code-input::after {
    order: 7;
}
.react-code-input input:nth-child(6) {
    order: 8;
}
.react-code-input input:nth-child(7) {
    order: 9;
}
.react-code-input input:nth-child(8) {
    order: 10;
}
```
